### ISSUE TITLE
我只想移除某个类库的nuget包，支持吗？

### ISSUE THREAD

**Issue by tanshanli** [shuhari/Nuget.UnlistAll#1]
例如解决方案有 Commone、WebUI、Core三个项目，他们都引用了 EntityFramework、log4net、Newtonsoft.Json三个nuget包。我现在只想移除Commone这个项目中的引用（不要影响其他项目引用）。

**Comment by shuhari** [comment]
抱歉，这个工具目的是移除 Nuget registry 中过时的历史列表，目标是包的开发者，并不是给用户管理解决方案用的。

Sorry that purpose of this program is to remove obsoluted history items in nuget registry, and targeting package developers. It's not for normal users to manage their solutions.

**Comment by tanshanli** [comment]
@shuhari 了解了，不过也挺实用。
